[package]
name = "grail"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
opt-level = 3

[dependencies]
chess = "3.2.0"
clap = { version = "4.5.23", features = ["derive"] }
log = "0.4.22"
lru = "0.12.5"
rand = "0.8.5"
rayon = "1.10.0"
simplelog = "0.12.2"
