[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
evaluation = { path = "../evaluation" }
uci = { path = "../uci" }

chess = { workspace = true }
ahash = { workspace = true }
log = { workspace = true }

[lib]
name = "search"
