[package]
name = "grail"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
opt-level = 3

[dependencies]
search = { path = "../search" }
nnue = { path = "../nnue" }
uci = { path = "../uci" }

ahash = { workspace = true }
chess = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
simplelog = { workspace = true }
